import { DropDownOption } from "../interfaces/dropdown";
import { AccidentalTypes } from "./notes";
import { KeyQuality } from "../interfaces/key";

export const DEFAULT_KEY = 'C';

export enum Keys {
    C = 'C',
    CSharp = 'C#',
    DFlat = 'Db',
    D = 'D',
    EFlat = 'Eb',
    E = 'E',
    F = 'F',
    FSharp = 'F#',
    GFlat = 'Gb',
    G = 'G',
    AFlat = 'Ab',
    A = 'A',
    BFlat = 'Bb',
    B = 'B'
}

export const scaleKeyQualityMap: Record<string, KeyQuality> = {
    'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    'C#Major': {key: Keys.CSharp, accidentalType: AccidentalTypes.Sharp},
    'DbMajor': {key: Keys.DFlat, accidentalType: AccidentalTypes.Flat},
    'DMajor': {key: Keys.D, accidentalType: AccidentalTypes.Natural},
    'D#Major': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    'EbMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    'EMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    'FMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    'F#Major': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    'GbMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    'GMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    'G#Major': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    'AbMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    'AMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    'A#Major': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    'BbMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    'BMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    'CMinor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    'C#Minor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    'DbMinor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    'DMinor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
    // 'CMajor': {key: Keys.C, accidentalType: AccidentalTypes.Natural},
};

export const keyOptions = (): DropDownOption[] => {
    const keys = [];
    for (let key of Object.values(Keys)) {
        keys.push({ label: key, value: key })
    }
    return keys;
};