import { NoteForScaleProps } from '../interfaces/scale';

// Might want to add scientific name to NoteForScaleProps object

export enum AccidentalType {
    Sharp,
    Flat,
    Natural
}

export const allNotesAndPitchNumbers: NoteForScaleProps[] = [
    {noteName: "A", abcName: "A,,,", pitchNumber: 33, accidentalType: AccidentalType.Natural},
    {noteName: "A#", abcName: "^A,,,", pitchNumber: 34, accidentalType: AccidentalType.Sharp},
    {noteName: "Bb", abcName: "_B,,,", pitchNumber: 34, accidentalType: AccidentalType.Flat},
    {noteName: "B", abcName: "B,,,", pitchNumber: 35, accidentalType: AccidentalType.Natural},
    {noteName: "C", abcName: "C,,", pitchNumber: 36, accidentalType: AccidentalType.Natural},
    {noteName: "C#", abcName: "^C,,", pitchNumber: 37, accidentalType: AccidentalType.Sharp},
    {noteName: "Db", abcName: "_D,,", pitchNumber: 37, accidentalType: AccidentalType.Flat},
    {noteName: "D", abcName: "D,,", pitchNumber: 38, accidentalType: AccidentalType.Natural},
    {noteName: "D#", abcName: "^D,,", pitchNumber: 39, accidentalType: AccidentalType.Sharp},
    {noteName: "Eb", abcName: "_E,,", pitchNumber: 39, accidentalType: AccidentalType.Flat},
    {noteName: "E", abcName: "E,,", pitchNumber: 40, accidentalType: AccidentalType.Natural},
    {noteName: "F", abcName: "F,,", pitchNumber: 41, accidentalType: AccidentalType.Natural},
    {noteName: "F#", abcName: "^F,,", pitchNumber: 42, accidentalType: AccidentalType.Sharp},
    {noteName: "Gb", abcName: "_G,,", pitchNumber: 42, accidentalType: AccidentalType.Flat},
    {noteName: "G", abcName: "G,,", pitchNumber: 43, accidentalType: AccidentalType.Natural},
    {noteName: "G#", abcName: "^G,,", pitchNumber: 44, accidentalType: AccidentalType.Sharp},
    {noteName: "Ab", abcName: "_A,,", pitchNumber: 44, accidentalType: AccidentalType.Flat},
    {noteName: "A", abcName: "A,,", pitchNumber: 45, accidentalType: AccidentalType.Natural},
    {noteName: "A#", abcName: "^A,,", pitchNumber: 46, accidentalType: AccidentalType.Sharp},
    {noteName: "Bb", abcName: "_B,,", pitchNumber: 46, accidentalType: AccidentalType.Flat},
    {noteName: "B", abcName: "B,,", pitchNumber: 47, accidentalType: AccidentalType.Natural},
    {noteName: "C", abcName: "C,", pitchNumber: 48, accidentalType: AccidentalType.Natural},
    {noteName: "C#", abcName: "^C,", pitchNumber: 49, accidentalType: AccidentalType.Sharp},
    {noteName: "Db", abcName: "_D,", pitchNumber: 49, accidentalType: AccidentalType.Flat},
    {noteName: "D", abcName: "D,", pitchNumber: 50, accidentalType: AccidentalType.Natural},
    {noteName: "D#", abcName: "^D,", pitchNumber: 51, accidentalType: AccidentalType.Sharp},
    {noteName: "Eb", abcName: "_E,", pitchNumber: 51, accidentalType: AccidentalType.Flat},
    {noteName: "E", abcName: "E,", pitchNumber: 52, accidentalType: AccidentalType.Natural},
    {noteName: "F", abcName: "F,", pitchNumber: 53, accidentalType: AccidentalType.Natural},
    {noteName: "F#", abcName: "^F,", pitchNumber: 54, accidentalType: AccidentalType.Sharp},
    {noteName: "Gb", abcName: "_G,", pitchNumber: 54, accidentalType: AccidentalType.Flat},
    {noteName: "G", abcName: "G,", pitchNumber: 55, accidentalType: AccidentalType.Natural},
    {noteName: "G#", abcName: "^G,", pitchNumber: 56, accidentalType: AccidentalType.Sharp},
    {noteName: "Ab", abcName: "_A,", pitchNumber: 56, accidentalType: AccidentalType.Flat},
    {noteName: "A", abcName: "A,", pitchNumber: 57, accidentalType: AccidentalType.Natural},
    {noteName: "A#", abcName: "^A,", pitchNumber: 58, accidentalType: AccidentalType.Sharp},
    {noteName: "Bb", abcName: "_B,", pitchNumber: 58, accidentalType: AccidentalType.Flat},
    {noteName: "B", abcName: "B,", pitchNumber: 59, accidentalType: AccidentalType.Natural},
    {noteName: "C", abcName: "C", pitchNumber: 60, accidentalType: AccidentalType.Natural},
    {noteName: "C#", abcName: "^C", pitchNumber: 61, accidentalType: AccidentalType.Sharp},
    {noteName: "Db", abcName: "_D", pitchNumber: 61, accidentalType: AccidentalType.Flat},
    {noteName: "D", abcName: "D", pitchNumber: 62, accidentalType: AccidentalType.Natural},
    {noteName: "D#", abcName: "^D", pitchNumber: 63, accidentalType: AccidentalType.Sharp},
    {noteName: "Eb", abcName: "_E", pitchNumber: 63, accidentalType: AccidentalType.Flat},
    {noteName: "E", abcName: "E", pitchNumber: 64, accidentalType: AccidentalType.Natural},
    {noteName: "F", abcName: "F", pitchNumber: 65, accidentalType: AccidentalType.Natural},
    {noteName: "F#", abcName: "^F", pitchNumber: 66, accidentalType: AccidentalType.Sharp},
    {noteName: "Gb", abcName: "_G", pitchNumber: 66, accidentalType: AccidentalType.Flat},
    {noteName: "G", abcName: "G", pitchNumber: 67, accidentalType: AccidentalType.Natural},
    {noteName: "G#", abcName: "^G", pitchNumber: 68, accidentalType: AccidentalType.Sharp},
    {noteName: "Ab", abcName: "_A", pitchNumber: 68, accidentalType: AccidentalType.Flat},
    {noteName: "A", abcName: "A", pitchNumber: 69, accidentalType: AccidentalType.Natural},
    {noteName: "A#", abcName: "^A", pitchNumber: 70, accidentalType: AccidentalType.Sharp},
    {noteName: "Bb", abcName: "_B", pitchNumber: 70, accidentalType: AccidentalType.Flat},
    {noteName: "B", abcName: "B", pitchNumber: 71, accidentalType: AccidentalType.Natural},
    {noteName: "C", abcName: "c", pitchNumber: 72, accidentalType: AccidentalType.Natural},
    {noteName: "C#", abcName: "^c", pitchNumber: 73, accidentalType: AccidentalType.Sharp},
    {noteName: "Db", abcName: "_d", pitchNumber: 73, accidentalType: AccidentalType.Flat},
    {noteName: "D", abcName: "d", pitchNumber: 74, accidentalType: AccidentalType.Natural},
    {noteName: "D#", abcName: "^d", pitchNumber: 75, accidentalType: AccidentalType.Sharp},
    {noteName: "Eb", abcName: "_e", pitchNumber: 75, accidentalType: AccidentalType.Flat},
    {noteName: "E", abcName: "e", pitchNumber: 76, accidentalType: AccidentalType.Natural},
    {noteName: "F", abcName: "f", pitchNumber: 77, accidentalType: AccidentalType.Natural},
    {noteName: "F#", abcName: "^f", pitchNumber: 78, accidentalType: AccidentalType.Sharp},
    {noteName: "Gb", abcName: "_g", pitchNumber: 78, accidentalType: AccidentalType.Flat},
    {noteName: "G", abcName: "g", pitchNumber: 79, accidentalType: AccidentalType.Natural},
    {noteName: "G#", abcName: "^g", pitchNumber: 80, accidentalType: AccidentalType.Sharp},
    {noteName: "Ab", abcName: "_a", pitchNumber: 80, accidentalType: AccidentalType.Flat},
    {noteName: "A", abcName: "a", pitchNumber: 81, accidentalType: AccidentalType.Natural},
    {noteName: "A#", abcName: "^a", pitchNumber: 82, accidentalType: AccidentalType.Sharp},
    {noteName: "Bb", abcName: "_b", pitchNumber: 82, accidentalType: AccidentalType.Flat},
    {noteName: "B", abcName: "b", pitchNumber: 83, accidentalType: AccidentalType.Natural},
    {noteName: "C", abcName: "c'", pitchNumber: 84, accidentalType: AccidentalType.Natural},
    {noteName: "C#", abcName: "^c'", pitchNumber: 85, accidentalType: AccidentalType.Sharp},
    {noteName: "Db", abcName: "_d'", pitchNumber: 85, accidentalType: AccidentalType.Flat},
    {noteName: "D", abcName: "d'", pitchNumber: 86, accidentalType: AccidentalType.Natural},
    {noteName: "D#", abcName: "^d'", pitchNumber: 87, accidentalType: AccidentalType.Sharp},
    {noteName: "Eb", abcName: "_e'", pitchNumber: 87, accidentalType: AccidentalType.Flat},
    {noteName: "E", abcName: "e'", pitchNumber: 88, accidentalType: AccidentalType.Natural},
    {noteName: "F", abcName: "f'", pitchNumber: 89, accidentalType: AccidentalType.Natural},
    {noteName: "F#", abcName: "^f'", pitchNumber: 90, accidentalType: AccidentalType.Sharp},
    {noteName: "Gb", abcName: "_g'", pitchNumber: 90, accidentalType: AccidentalType.Flat},
    {noteName: "G", abcName: "g'", pitchNumber: 91, accidentalType: AccidentalType.Natural},
    {noteName: "G#", abcName: "^g'", pitchNumber: 92, accidentalType: AccidentalType.Sharp},
    {noteName: "Ab", abcName: "_a'", pitchNumber: 92, accidentalType: AccidentalType.Flat},
    {noteName: "A", abcName: "a'", pitchNumber: 93, accidentalType: AccidentalType.Natural},
    {noteName: "A#", abcName: "^a'", pitchNumber: 94, accidentalType: AccidentalType.Sharp},
    {noteName: "Bb", abcName: "_b'", pitchNumber: 94, accidentalType: AccidentalType.Flat},
    {noteName: "B", abcName: "b'", pitchNumber: 95, accidentalType: AccidentalType.Natural},
    {noteName: "C", abcName: "c''", pitchNumber: 96, accidentalType: AccidentalType.Natural},
    {noteName: "C#", abcName: "^c''", pitchNumber: 97, accidentalType: AccidentalType.Sharp},
    {noteName: "Db", abcName: "_d''", pitchNumber: 97, accidentalType: AccidentalType.Flat},
    {noteName: "D", abcName: "d''", pitchNumber: 98, accidentalType: AccidentalType.Natural},
    {noteName: "D#", abcName: "^d''", pitchNumber: 99, accidentalType: AccidentalType.Sharp},
    {noteName: "Eb", abcName: "_e''", pitchNumber: 99, accidentalType: AccidentalType.Flat},
    {noteName: "E", abcName: "e''", pitchNumber: 100, accidentalType: AccidentalType.Natural}
]